// Code generated by girgen. DO NOT EDIT.

package gst

import (
	"runtime"
)

// #include <stdlib.h>
// #include <gst/gst.h>
import "C"

// EventTypeToStickyOrdering converts the EventType to an unsigned integer that
// represents the ordering of sticky events when re-sending them. A lower value
// represents a higher-priority event.
//
// The function takes the following parameters:
//
//   - typ: EventType.
//
// The function returns the following values:
//
//   - guint: unsigned integer.
//
func EventTypeToStickyOrdering(typ EventType) uint {
	var _arg1 C.GstEventType // out
	var _cret C.guint        // in

	_arg1 = C.GstEventType(typ)

	_cret = C.gst_event_type_to_sticky_ordering(_arg1)
	runtime.KeepAlive(typ)

	var _guint uint // out

	_guint = uint(_cret)

	return _guint
}
