// Code generated by girgen. DO NOT EDIT.

package gst

// #include <stdlib.h>
// #include <gst/gst.h>
import "C"

// META_TAG_MEMORY_REFERENCE_STR: this metadata stays relevant until a deep copy
// is made.
const META_TAG_MEMORY_REFERENCE_STR = "memory-reference"
