// Code generated by girgen. DO NOT EDIT.

package gstvideo

import (
	"runtime"
	"unsafe"

	"github.com/OmegaRogue/gotk4-gstreamer/pkg/gst"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
)

// #include <stdlib.h>
// #include <gst/video/video.h>
import "C"

// VideoOrientationFromTag parses the "image-orientation" tag and transforms it
// into the VideoOrientationMethod enum.
//
// The function takes the following parameters:
//
//   - taglist: TagList.
//
// The function returns the following values:
//
//   - method: location where to return the orientation.
//   - ok: TRUE if there was a valid "image-orientation" tag in the taglist.
//
func VideoOrientationFromTag(taglist *gst.TagList) (VideoOrientationMethod, bool) {
	var _arg1 *C.GstTagList               // out
	var _arg2 C.GstVideoOrientationMethod // in
	var _cret C.gboolean                  // in

	_arg1 = (*C.GstTagList)(gextras.StructNative(unsafe.Pointer(taglist)))

	_cret = C.gst_video_orientation_from_tag(_arg1, &_arg2)
	runtime.KeepAlive(taglist)

	var _method VideoOrientationMethod // out
	var _ok bool                       // out

	_method = VideoOrientationMethod(_arg2)
	if _cret != 0 {
		_ok = true
	}

	return _method, _ok
}
