// Code generated by girgen. DO NOT EDIT.

package gstvideo

import (
	"runtime"
)

// #include <stdlib.h>
// #include <gst/video/video.h>
import "C"

// VideoIsCommonAspectRatio: given a frame's dimensions and pixel aspect ratio,
// this function will calculate the frame's aspect ratio and compare it against
// a set of common well-known "standard" aspect ratios.
//
// The function takes the following parameters:
//
//   - width: width of the video frame.
//   - height: height of the video frame.
//   - parN: pixel aspect ratio numerator.
//   - parD: pixel aspect ratio denominator.
//
// The function returns the following values:
//
//   - ok: TRUE if a known "standard" aspect ratio was recognised, and FALSE
//     otherwise.
//
func VideoIsCommonAspectRatio(width, height, parN, parD int) bool {
	var _arg1 C.gint     // out
	var _arg2 C.gint     // out
	var _arg3 C.gint     // out
	var _arg4 C.gint     // out
	var _cret C.gboolean // in

	_arg1 = C.gint(width)
	_arg2 = C.gint(height)
	_arg3 = C.gint(parN)
	_arg4 = C.gint(parD)

	_cret = C.gst_video_is_common_aspect_ratio(_arg1, _arg2, _arg3, _arg4)
	runtime.KeepAlive(width)
	runtime.KeepAlive(height)
	runtime.KeepAlive(parN)
	runtime.KeepAlive(parD)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}
