// Code generated by girgen. DO NOT EDIT.

package gstvideo

import (
	"runtime"
)

// #include <stdlib.h>
// #include <gst/video/video.h>
import "C"

// VideoColorPrimariesIsEquivalent checks whether primaries and other are
// functionally equivalent.
//
// The function takes the following parameters:
//
//   - primaries: VideoColorPrimaries.
//   - other VideoColorPrimaries.
//
// The function returns the following values:
//
//   - ok: TRUE if primaries and other can be considered equivalent.
//
func VideoColorPrimariesIsEquivalent(primaries, other VideoColorPrimaries) bool {
	var _arg1 C.GstVideoColorPrimaries // out
	var _arg2 C.GstVideoColorPrimaries // out
	var _cret C.gboolean               // in

	_arg1 = C.GstVideoColorPrimaries(primaries)
	_arg2 = C.GstVideoColorPrimaries(other)

	_cret = C.gst_video_color_primaries_is_equivalent(_arg1, _arg2)
	runtime.KeepAlive(primaries)
	runtime.KeepAlive(other)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}
