// Code generated by girgen. DO NOT EDIT.

package gstaudio

// #include <stdlib.h>
// #include <gst/audio/audio.h>
import "C"

// AUDIO_CONVERTER_OPT_DITHER_THRESHOLD: threshold for the output bit depth
// at/below which to apply dithering.
//
// Default is 20 bit.
const AUDIO_CONVERTER_OPT_DITHER_THRESHOLD = "GstAudioConverter.dither-threshold"
